---
- name: Join a system to the domain
  hosts: windows_workstation
  gather_facts: no
  vars_prompt:
  - name: adminpassword
    prompt: What will be the password for local and domain administrator?
    private: yes

  tasks:
  # - name: Change DNS Server
  #   win_dns_client:
  #     adapter_names: Ethernet0
  #     ipv4_addresses: 10.0.5.5

  - name: Join the domain
    win_domain_membership:
      dns_domain_name: blue8.local
      domain_admin_user: deployer@blue8.local
      domain_admin_password: "{{ adminpassword }}"
      domain_ou_path: "OU=Workstations,OU=Computers,OU=blue8,DC=blue8,DC=local"
      state: domain
    register: domain_state 

  - name: Reboot when required
    when: domain_state.reboot_required
    win_reboot:
      connect_timeout: 15
      post_reboot_delay: 15
      reboot_timeout: 200
      msg: "Server config in process: rebooting..."