---
- name: Install nginx on AWS Ubuntu Server
  hosts: aws

  tasks:
  - name: Install nginx
    apt: name=nginx state=latest
    become: yes

  - name: Start nginx
    service:
      name: nginx
      state: started
    become: yes