- name: parsecsv
  hosts: domain_controller
  vars_prompt:
  - name: path
    prompt: Enter the path to the CSV file
    private: no

  tasks:
  - name: add domain admin
    win_domain_user:
      name: blue8-demo
      password: "{{ password }}"
      password_never_expires: yes
      state: present
      path: "OU=Accounts,DC=blue8,DC=local"
      groups: 
        - Domain Admins
 
  - name: read csv file
    read_csv:
      path: "{{ path }}"
    register: items
    delegate_to: localhost

  - name: add users
    debug:
      msg: "{{item.password}} - {{ item.username }} - {{ item.group }}"
    with_items: "{{ items.list }}"