---
- name: rdp
  hosts: 
  - vanhalen
  - windows_workstation
  
  tasks:
  - name: Enable rdp
    win_group_membership:
      name: Remote Desktop Users
      members:
      - BLUE8\Domain Users

  - name: rdp firewall
    win_shell: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"


