---
- name: Install and configure chocolatey on Windows Workstations
  hosts: windows_workstation

  tasks:
  - name: Install Chocolatey Packages
    win_chocolatey:
      name:
      - 7zip
      - googlechrome
      - vscode
      - putty
      - python3
      - git
      - notepadplusplus
      state: latest