---
- name: Install and configure chocolatey on Windows Workstations
  hosts: windows_workstation
  gather_facts: no

  tasks:
    - name: Install Chocolatey Packages
      win_chocolatey:
        name:
        - 7zip
        - googlechrome
        - vscode
        - putty
        - python3
        - git
        - notepadplusplus
        state: present